spring:
  datasource:
    url: jdbc:${MYSQL_URL}?createDatabaseIfNotExist=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    validate-on-migrate: false
    baseline-on-migrate: true